### ISSUE TITLE
Generate Contact Grasps and Scenes yourself

### ISSUE THREAD

**Issue by styczenavena** [NVlabs/contact_graspnet#15]
Hi,

Im running into an issue while trying to generate contant grasps and scenens myslef. I want use my own gripper.

Steps I did:
1. Download Acronym dataset
2. run python tools/create_contact_infos.py /home/avena/Downloads/acronym
and I'm getting following error:

```
Root folder /home/avena/Downloads/acronym/
Failed to establish dbus connectionComputing grasp contacts...
Reading:  /home/avena/Downloads/acronym/grasps/Chair_47ac4f73d91f8ff0c862eec8232fff1e_0.006926674889814925.h5
positive grasps: (1837, 4, 4) negative grasps: (163, 4, 4)
Traceback (most recent call last):
  File "tools/create_contact_infos.py", line 124, in <module>
    save_contact_data(pcreader, grasp_path)
  File "tools/create_contact_infos.py", line 95, in save_contact_data
    pcreader.change_object(cad_path, cad_scale)
  File "/home/avena/software/contact_graspnet/contact_graspnet/data.py", line 679, in change_object
    self._renderer.change_object(cad_path, cad_scale)
AttributeError: 'SceneRenderer' object has no attribute 'change_object'
********** terminating renderer **************
```
Do I need to  download ShapeNet meshes and make them watertight too?

**Comment by MartinSmeyer** [comment]
yes you need to follow all steps described in the Readme :-)

https://github.com/NVlabs/contact_graspnet#download-data
